version: "3.9"

services:
  db:
    image: tinh08042005/learninglanguage-db:withdata
    platform: linux/amd64
    container_name: sqlserver-db
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P '@Tinh0804' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
    environment:
      SA_PASSWORD: "@Tinh0804"
      ACCEPT_EULA: "Y"
    volumes:
      - nhom_sql_data:/var/opt/mssql 
    networks:
      - appnet

  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: tinh08042005/learninglanguage:latest
    container_name: backend-api
    depends_on:
      - db
    ports:
      - "5050:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=AppLearning;User Id=sa;Password=@Tinh0804;MultipleActiveResultSets=true;TrustServerCertificate=True

    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  nhom_sql_data:
    external: true
    name: nhom_sql_data
